# Change these first
owner: jobsonlook # Your GitHub organization or username, where this repository lives
repo: ttt-upptime # The name of this repository

sites:
  - name: data-ens-indexer
    url: $LAMBDA_MONIT_SERVER_URL?server=ens_indexer
  - name: data-crypto-event
    url: $LAMBDA_MONIT_SERVER_URL?server=crypto_event
  - name: data-twitter-tips
    url: $LAMBDA_MONIT_SERVER_URL?server=twitter_tips
  - name: msk-connector
    url: $LAMBDA_MONIT_SERVER_URL?server=msk_connector
  - name: glue
    url: $LAMBDA_MONIT_SERVER_URL?server=glue

status-website:
  # # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: jobsonlook.github.io
  baseUrl: /ttt-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ttt-upptime
  introTitle: "ttt-upptime"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
